### ISSUE TITLE
Event blocks not working as expected

### ISSUE THREAD

**Issue by MikeDev101** [FurryR/scratch-ext#2]
Hello,

I was porting [cloudlink-omega/cl5](https://github.com/cloudlink-omega/cl5) to TS using your scaffolding. 
After redefining block types with Scratch.BlockType I couldn't get EVENT blocks to work.

e.g.
```
{
            opcode: 'on_signalling_connect',
            blockType: Scratch.BlockType.EVENT,
            text: 'When I am connected to signaling server'
}
```

when I leave this statement as-is, I see a message saying

`Property 'isEdgeActivated' is optional in type '{ opcode: string; blockType: "event"; text: string; arguments?: undefined; isEdgeActivated?: undefined; }' but required in type 'EventBlock'.`

When I modify the statement to

```
{
            opcode: 'on_signalling_connect',
            blockType: Scratch.BlockType.EVENT,
            text: 'When I am connected to signaling server',
            isEdgeActivated: false,
}
```

I get these other errors:

`Types of property 'isEdgeActivated' are incompatible.
Type 'boolean' is not assignable to type 'false'.`

The only time these blocks work is if I override typescript checking with `// @ts-ignore` for `getInfo()`.

**Comment by FurryR** [comment]
It is an upstream issue referring to [`@turbowarp/types`](https://github.com/Turbowarp/types). Please check if you can reproduce the problem in [`extensions`](https://github.com/Turbowarp/extensions)?

**Comment by FurryR** [comment]
It seems to be fixed after I switch type definitions to `@types/tw`.
Please let me know if the issue presists.
