### ISSUE TITLE
turbowarp拓展PR eslint检查无法通过

### ISSUE THREAD

**Issue by skydog221** [FurryR/scratch-ext#3]
所有检查、修复命令都执行过了
但turbowarp的cli自动检测还是过不了
https://github.com/TurboWarp/extensions/pull/1404
![image](https://github.com/FurryR/scratch-ext/assets/121487216/e09acd1f-9a96-45d1-a878-c59182b970df)
![image](https://github.com/FurryR/scratch-ext/assets/121487216/56a8cc9e-e2b9-4d83-b08e-b01fa63f6930)

注：为了适配双平台，没有动优化选项

**Comment by FurryR** [comment]
1. 需要手动为函数体添加 `'use strict';` 严格模式声明
2. 应该使用 `Scratch.fetch`（仅 Turbowarp） 而将 `fetch` 作为备用，`Scratch.fetch` 将连接到 Turbowarp 的安全管理器
